services:
  # Backend Service
  - type: web
    name: tradeverse-backend
    runtime: node
    plan: free
    branch: main
    rootDir: tradeverse-backend
    buildCommand: npm install
    startCommand: node server.js
    startCommand: node server.js
    envGroups:
      - "TradeVerse Backend environment data"
    envVars:
      - key: FRONTEND_URL
        fromService:
          type: static
          name: tradeverse-frontend
          property: url

  # Frontend Service
  - type: static
    name: tradeverse-frontend
    branch: main
    rootDir: tradeverse-frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envGroups:
      - "TradeVerse Frontend environment data"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: tradeverse-backend
          property: url
